# -*- coding: utf-8 -*-
"""generative-ai-etl-pipeline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1su3sYmW3-YTk7CZRrD5uJnt7rEQrVZfo

## Explorando IA Generativa com Python e compreendendo o fluxo ETL
"""

import pandas as pd
from google import genai
import os
import json
from dotenv import load_dotenv

load_dotenv()

"""### Extração de Dados

#### Contexto do Desafio: Você é um cientista de dados no Santander e recebeu a tarefa de envolver seus clientes de maneira mais personalizada. Seu objetivo é usar o poder da IA Generativa para criar mensagens de marketing personalizadas que serão entregues a cada cliente.

"""

import random

# Simula a extração de dados

users_list = []

naruto_user = {
    'id': 1,
    'name': 'Naruto',
    'account': {
        'number': f'{random.randint(10000, 99999)}-{random.randint(1, 9)}',
        'agency': '0001',
        'balance': round(random.uniform(0, 10000), 2),
        'limit': round(random.uniform(500, 5000), 2)
    },
    'card': {
        'number': f'****-****-****-{random.randint(1000, 9999)}',
        'limit': round(random.uniform(1000, 10000), 2)
    },
    'features': [],
    'news': []
}
users_list.append(naruto_user)

hinata_user = {
    'id': 2,
    'name': 'Hinata',
    'account': {
        'number': f'{random.randint(10000, 99999)}-{random.randint(1, 9)}',
        'agency': '0001',
        'balance': round(random.uniform(0, 10000), 2),
        'limit': round(random.uniform(500, 5000), 2)
    },
    'card': {
        'number': f'****-****-****-{random.randint(1000, 9999)}',
        'limit': round(random.uniform(1000, 10000), 2)
    },
    'features': [],
    'news': []
}
users_list.append(hinata_user)


for i in range(3, 6):
    user_data = {
        'id': i,
        'name': f'User {i}',
        'account': {
            'number': f'{random.randint(10000, 99999)}-{random.randint(1, 9)}',
            'agency': '0001',
            'balance': round(random.uniform(0, 10000), 2),
            'limit': round(random.uniform(500, 5000), 2)
        },
        'card': {
            'number': f'****-****-****-{random.randint(1000, 9999)}',
            'limit': round(random.uniform(1000, 10000), 2)
        },
        'features': [],
        'news': []
    }
    users_list.append(user_data)


users = tuple(users_list)

"""### Transformação

#### Utilizando a API do Google Gemini para gerar uma mensagem de marketing personalizada para cada usuário
"""

client = genai.Client()

def generate_ai_news(user):

  prompt = f"Você é um especialista em marketing bancário. Crie uma mensagem para {user['name']} sobre a importância dos investimentos ou dicas gerais sobre gerenciamento de conta e segurança (máximo de 100 caracteres)"

  try:
    response = client.models.generate_content(
        model='gemini-2.0-flash',
        contents=prompt
    )
    return response.text
  except Exception as e:
    print(f"Erro ao gerar notícia para {user['name']}: {e}")
    return "Não foi possível gerar uma mensagem personalizada no momento."

# print(generate_ai_news(users[0])) - Saída: Naruto, proteja seu futuro! Invista com sabedoria e fique atento à segurança da sua conta, dattebayo! 😉


"""### Load

#### Atualizando a lista de "news" de cada usuário com a nova mnesagem gerada e exibindo seu resultado localmente
"""

for user_data in users:
  generated_news = generate_ai_news(user_data)
  user_data['news'].append(generated_news)

print(users)

with open('users_data.json', 'w', encoding='utf-8') as f:
    json.dump(users, f, indent=2, ensure_ascii=False)